[package]
name = "gitbutler-id"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
[dependencies]
serde = { workspace = true, features = ["std"]}
uuid.workspace = true
