[package]
name = "gitbutler-storage"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
[dependencies]
gitbutler-fs.workspace = true
