[package]
name = "but-rebase"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
[lib]
doctest = false

[dependencies]
gix = { workspace = true, features = ["revision", "merge"]}
anyhow.workspace = true
tracing.workspace = true
but-core.workspace = true
gitbutler-oxidize.workspace = true
gitbutler-error.workspace = true
bstr.workspace = true
tempfile.workspace = true
serde = { version = "1.0.228", features = ["derive"] }
toml.workspace = true
but-gerrit.workspace = true

[dev-dependencies]
but-testsupport.workspace = true
insta = "1.43.2"
but-core = { workspace = true, features = ["testing"] }
