[package]
name = "but"
version = "0.0.0"
edition = "2024"
repository = "https://github.com/gitbutlerapp/gitbutler"
license-file = "../../LICENSE.md"
description = "A GitButler CLI tool"
authors = ["GitButler <gitbutler@gitbutler.com>"]
readme = "../../README.md"
publish = false
rust-version = "1.89"
[[bin]]
name = "but"
path = "src/main.rs"
doctest = false

[features]

[dependencies]
posthog-rs = { version = "0.3.7" }
serde.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "io-std"] }
tokio-util = "0.7.16"
strum = { version = "0.27", features = ["derive"] }
clap = { version = "4.5.48", features = ["derive", "env"] }
chrono = { version = "0.4.42" }
bstr.workspace = true
regex = "1.11.3"
anyhow.workspace = true
# rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk", branch = "main" }
rmcp.workspace = true
command-group = { version = "5.0.1", features = ["with-tokio"] }
sysinfo = "0.37.1"
gitbutler-project.workspace = true
gix.workspace = true
but-core.workspace = true
but-api.workspace = true
but-db.workspace = true
but-action.workspace = true
but-graph.workspace = true
but-workspace.workspace = true
but-settings.workspace = true
but-hunk-assignment.workspace = true
but-hunk-dependency.workspace = true
but-claude.workspace = true
but-cursor.workspace = true
but-tools.workspace = true
but-rules.workspace = true
gitbutler-command-context.workspace = true
gitbutler-serde.workspace = true
gitbutler-commit.workspace = true
gitbutler-stack.workspace = true
gitbutler-branch-actions.workspace = true
gitbutler-branch.workspace = true
gitbutler-secret.workspace = true
gitbutler-oxidize.workspace = true
gitbutler-oplog.workspace = true
colored = "3.0.0"
serde_json = "1.0.145"
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "std",
    "fmt",
] }
dirs-next = "2.0.0"
