[package]
name = "gitbutler-stack"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
autotests = false

[dependencies]
git2.workspace = true
gix = { workspace = true, features = [] }
itertools = "0.14"
anyhow = "1.0.100"
serde = { workspace = true, features = ["std"] }
toml.workspace = true
gitbutler-reference.workspace = true
but-core.workspace = true
but-rebase.workspace = true
but-graph.workspace = true
gitbutler-time.workspace = true
gitbutler-diff.workspace = true
gitbutler-error.workspace = true
gitbutler-fs.workspace = true
gitbutler-command-context.workspace = true
gitbutler-repo.workspace = true
gitbutler-commit.workspace = true
gitbutler-oxidize.workspace = true
bstr.workspace = true

[[test]]
name = "stack"
path = "tests/mod.rs"

[dev-dependencies]
gitbutler-git = { workspace = true, features = [
    "test-askpass-path",
] } # Runtime test dependency
gitbutler-testsupport.workspace = true
gitbutler-repo-actions.workspace = true
tempfile.workspace = true
