[package]
name = "gitbutler-oxidize"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
[dependencies]
anyhow.workspace = true
git2.workspace = true
gix = { workspace = true, features = ["merge"] }
