name: build e2e-runner container
on:
  push:
    branches:
      - master
    paths:
      - 'e2e/blackbox/Dockerfile'

jobs:
  docker_publish:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          context: 'e2e/blackbox/Dockerfile'
          push: true
          tags: ghcr.io/gitbutler/e2e-runner:latest
